app/note/urls.py
from django.conf.urls import patterns, url

from app.note import views

urlpatterns = patterns('',
    # /note
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

djhaystack/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djhaystack.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', RedirectView.as_view(url='note/', permanent=False), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^note/', include('app.note.urls', namespace='note')),
    url(r'^search/', include('haystack.urls')),
)

app/note/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


class Note(models.Model):
    user = models.ForeignKey('auth.User')
    pub_date = models.DateTimeField('date created', default=timezone.now)
    title = models.CharField(max_length=200)
    body = models.TextField()

    class Meta:
        get_latest_by = 'pub_date'
        ordering = ('-pub_date',)
        verbose_name_plural = 'notes'

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('note:detail', args=[str(self.id)])

app/note/views.py
from django.shortcuts import render
from django.views import generic
from django.utils import timezone
from app.note.models import Note


class IndexView(generic.ListView):
    template_name = 'note/index.html'
    context_object_name = 'latest_notes'

    def get_queryset(self):
        """ return latest notes """
        return Note.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Note
    template_name = 'note/detail.html'

    def get_queryset(self):
        """ return latest notes """
        return Note.objects.filter(pub_date__lte=timezone.now())

app/note/templates/base.html
{% load staticfiles %}

{% block content %}

{% endblock content %}

app/note/templates/note/detail.html
{% load static %}

<h1>{{ note.title }}</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<h3>by User on {{ note.pub_date }}</h3>

{{ note.body }}

<p>
    <a href="{% url 'note:index' %}">Note index</a>
</p>

app/note/templates/note/index.html
{% load staticfiles %}

{% if latest_notes %}
    <ul>
        {% for note in latest_notes %}
            <li><a href="{% url 'note:detail' note.id %}">{{ note.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No notes are available.</p>
{% endif %}

<p>
    <a href="/search">Search</a>
</p>

app/note/templates/search/search.html
{% extends "base.html" %}

{% block content %}
    <h2>Search</h2>

    <form method="get" action=".">
        <table>
            {{ form.as_table }}
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search">
                </td>
            </tr>
        </table>

        {% if query %}
            <h3>Results</h3>

            {% for result in page.object_list %}
                <p>
                    <a href="{{ result.object.get_absolute_url }}">{{ result.object.title }}</a>
                </p>
            {% empty %}
                <p>No results found.</p>
            {% endfor %}

            {% if page.has_previous or page.has_next %}
                <div>
                    {% if page.has_previous %}
                        <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">
                    {% endif %}
                        &laquo; Previous
                    {% if page.has_previous %}
                        </a>
                    {% endif %}
                    |
                    {% if page.has_next %}
                        <a href="?q={{ query }}&amp;page={{ page.next_page_number }}">
                    {% endif %}
                        Next &raquo;
                    {% if page.has_next %}
                        </a>
                    {% endif %}
                </div>
            {% endif %}

        {% else %}
            {# <p>No queries found.</p> #}
        {% endif %}

    </form>
{% endblock content %}